### ISSUE TITLE
DoctorKafka fails to start NullPointerException  at getProcessingStartOffsets

### ISSUE THREAD

**Issue by saherahwal** [pinterest/doctorkafka#227]
Hi

I got DoctorKafka to run previously with one broker on my local machine. I added two other brokers on same IP different ports. (Total kafka cluster with 1 zk node and 3 brokers). Doctor Kafka fails to start with below.

```
12:44:49.344 [pool-8-thread-1] ERROR com.pinterest.doctorkafka.DoctorKafkaMain - DoctorKafka start failed
java.lang.NullPointerException: null
        at com.pinterest.doctorkafka.util.ReplicaStatsUtil.getProcessingStartOffsets(ReplicaStatsUtil.java:28) ~[doctorkafka-0.2.4.9.jar:?]
        at com.pinterest.doctorkafka.replicastats.ReplicaStatsManager.readPastReplicaStats(ReplicaStatsManager.java:82) ~[doctorkafka-0.2.4.9.jar:?]
        at com.pinterest.doctorkafka.DoctorKafka.start(DoctorKafka.java:56) ~[doctorkafka-0.2.4.9.jar:?]
        at com.pinterest.doctorkafka.DoctorKafkaMain.lambda$run$0(DoctorKafkaMain.java:78) ~[doctorkafka-0.2.4.9.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
INFO  [2020-05-29 19:44:49,356] org.eclipse.jetty.setuid.SetUIDListener: Opened application@359066bc{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
INFO  [2020-05-29 19:44:49,359] org.eclipse.jetty.server.Server: jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_252-8u252-b09-1~18.04-b09
INFO  [2020-05-29 19:44:49,812] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:
```

**Comment by ambud** [comment]
Dr. Kafka wasn't designed to have single node multi-broker operations so ideally your brokers should be well distributed across nodes with 1 broker per node.

**Comment by saherahwal** [comment]
Ok I understand that but it should not fail with NPE. Since this is valid Kafka setup for dev box.
