### ISSUE TITLE
0.2.4.2 kafkastats missing com/fasterxml/jackson/annotation/JsonMerge

### ISSUE THREAD

**Issue by BrianGallew** [pinterest/doctorkafka#70]
Running the jar from https://repo.maven.apache.org/maven2/com/github/pinterest/kafkastats/0.2.4.2/kafkastats-0.2.4.2-jar-with-dependencies.jar, I get the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
	at kafka.utils.Json$.<init>(Json.scala:30)
	at kafka.utils.Json$.<clinit>(Json.scala)
	at kafka.zk.BrokerIdZNode$.decode(ZkData.scala:193)
	at kafka.utils.ZkUtils.parseBrokerJson(ZkUtils.scala:708)
	at kafka.utils.ZkUtils.getBrokerInfo(ZkUtils.scala:871)
	at kafka.utils.ZkUtils.$anonfun$getAllBrokersInCluster$2(ZkUtils.scala:280)
	at kafka.utils.ZkUtils.$anonfun$getAllBrokersInCluster$2$adapted(ZkUtils.scala:280)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:280)
	at com.pinterest.doctorkafka.util.OperatorUtil.getBrokers(OperatorUtil.java:214)
	at com.pinterest.doctorkafka.util.OperatorUtil.createKafkaProducerProperties(OperatorUtil.java:226)
	at com.pinterest.doctorkafka.stats.KafkaAvroPublisher.<init>(KafkaAvroPublisher.java:60)
	at com.pinterest.doctorkafka.stats.KafkaStatsMain.main(KafkaStatsMain.java:132)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonMerge
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

**Comment by saherahwal** [comment]
this issue should be reopened. 

looks like jackson dependency is removed by following commit.

```
commit a744e501d5a0908eb5a0e9da5750f437e879ac49
Author: kabochya <kabochya@users.noreply.github.com>
Date:   Fri Sep 27 15:41:49 2019 -0700

    bump dropwizard version to 1.3.15 and remove patch dependencies of jetty and jackson (#187)
```
