### ISSUE TITLE
labels and metrics missing in stats.txt

### ISSUE THREAD

**Issue by yhzhao** [pinterest/doctorkafka#82]
curl localhost:2051/stats.txt

counters:
  jvm_gc_G1_Old_Generation_cycles: 0
  jvm_gc_G1_Old_Generation_msec: 0
  jvm_gc_G1_Young_Generation_cycles: 4
  jvm_gc_G1_Young_Generation_msec: 22
  jvm_gc_cycles: 4
  jvm_gc_msec: 22
  kafka.stats.collector.success host=ATH021430: 3
gauges:
  jvm_buffer_direct_count: 7
  jvm_buffer_direct_max: 11238
  jvm_buffer_direct_used: 11238
  jvm_buffer_mapped_count: 0
  jvm_buffer_mapped_max: 0
  jvm_buffer_mapped_used: 0
  jvm_classes_current_loaded: 5646
  jvm_classes_total_loaded: 5646
  jvm_classes_total_unloaded: 0
  jvm_compilation_time_msec: 4092
  jvm_current_mem_CodeHeap__non_nmethods__max: 5836800
  jvm_current_mem_CodeHeap__non_nmethods__used: 1295104
  jvm_current_mem_CodeHeap__non_profiled_nmethods__max: 122912768
  jvm_current_mem_CodeHeap__non_profiled_nmethods__used: 1245952
  jvm_current_mem_CodeHeap__profiled_nmethods__max: 122908672
  jvm_current_mem_CodeHeap__profiled_nmethods__used: 5857920
  jvm_current_mem_Compressed_Class_Space_max: 1073741824
  jvm_current_mem_Compressed_Class_Space_used: 4882000
  jvm_current_mem_G1_Eden_Space_max: -1
  jvm_current_mem_G1_Eden_Space_used: 45088768
  jvm_current_mem_G1_Old_Gen_max: 4294967296
  jvm_current_mem_G1_Old_Gen_used: 5705664
  jvm_current_mem_G1_Survivor_Space_max: -1
  jvm_current_mem_G1_Survivor_Space_used: 4194304
  jvm_current_mem_Metaspace_max: -1
  jvm_current_mem_Metaspace_used: 38412688
  jvm_current_mem_used: 106682400
  jvm_fd_count: 28
  jvm_fd_limit: 10240
  jvm_heap_committed: 268435456
  jvm_heap_max: 4294967296
  jvm_heap_used: 53940160
  jvm_nonheap_committed: 56143872
  jvm_nonheap_max: -1
  jvm_nonheap_used: 51693664
  jvm_num_cpus: 8
  jvm_post_gc_G1_Eden_Space_max: -1
  jvm_post_gc_G1_Eden_Space_used: 0
  jvm_post_gc_G1_Old_Gen_max: 4294967296
  jvm_post_gc_G1_Old_Gen_used: 0
  jvm_post_gc_G1_Survivor_Space_max: -1
  jvm_post_gc_G1_Survivor_Space_used: 4194304
  jvm_post_gc_used: 4194304
  jvm_start_time: 1547650392880
  jvm_thread_count: 63
  jvm_thread_daemon_count: 18
  jvm_thread_peak_count: 63
  jvm_uptime: 165103
labels:
metrics:

There is exception reported by kafkastats process.

**Comment by yuyang08** [comment]
@yhzhao  can you provide more details on the exceptions that you saw w.r.t kafkastats?

**Comment by yhzhao** [comment]
The exception is caused by metadata binary not found, since I run it on my laptop.

**Comment by yhzhao** [comment]
ERROR com.pinterest.doctorkafka.stats.BrokerStatsRetriever - Failed to get ec2 metadata
java.io.IOException: Cannot run program "ec2metadata": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:591) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:415) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:312) ~[?:?]
	at com.pinterest.doctorkafka.stats.BrokerStatsRetriever.setBrokerInstanceInfo(BrokerStatsRetriever.java:368) [kafkastats-0.2.4-jar-with-dependencies.jar:?]
	at com.pinterest.doctorkafka.stats.BrokerStatsRetriever.retrieveBrokerStats(BrokerStatsRetriever.java:537) [kafkastats-0.2.4-jar-with-dependencies.jar:?]
	at com.pinterest.doctorkafka.stats.BrokerStatsReporter.run(BrokerStatsReporter.java:55) [kafkastats-0.2.4-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:271) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[?:?]
	... 13 more
Jan 16, 2019 10:01:34 AM com.twitter.ostrich.admin.BackgroundProcess start
INFO: Starting LatchedStatsListener
Jan 16, 2019 10:01:34 AM com.twitter.ostrich.admin.AdminHttpService start
INFO: Admin HTTP interface started on port 2051.

**Comment by yhzhao** [comment]
When running on a real ec2 instance, there is no exception, but the output of curl stats.txt remains similar. The metric or tag sections are empty.

What does a good stats.txt look like, by the way?

**Comment by yuyang08** [comment]
The stats that you posted earlier looks right.  `kafka.stats.collector.success host=ATH021430: 3` show that kafkastats had successfully reported 3 stats message.
